### ISSUE TITLE
Keine Anzeige nach Installation

### ISSUE THREAD

**Issue by testit2020** [oweitman/iobroker.tvprogram#12]
Keinerlei Anzeige in der Instanz und in den Objekten:
![image](https://user-images.githubusercontent.com/68483974/104825058-be1e7c00-5857-11eb-866d-253f8e99a9fb.png)

![image](https://user-images.githubusercontent.com/68483974/104825066-cc6c9800-5857-11eb-999d-f11250a3d783.png)

Objekte:

![image](https://user-images.githubusercontent.com/68483974/104825074-d7bfc380-5857-11eb-8aae-1b6155bc9985.png)

Instanz:

![image](https://user-images.githubusercontent.com/68483974/104825079-e7d7a300-5857-11eb-9b13-ddccf8169527.png)

**Comment by oweitman** [comment]
Aus der Readme:

Adapter Configuration
No configuration currently required

**Comment by testit2020** [comment]
Wann holt er sich denn die Daten? In den Objekten steht nichts.

**Comment by oweitman** [comment]
Verfolge bitte den Testthread, da habe ich life berichtet.
https://forum.iobroker.net/topic/40168/test-adapter-tvprogram/

Die Daten werden nicht in Datenpunkte geschrieben, da es pro Tag bis zu 2,5MB sind. Das ist zuviel für einen Datenpunkt.
Die Datenwerden nun per sendto vom widget beim adapter abgefragt.
Aber wie gesagt, Details stehen im Testthread.
Aktuell sind wir noch alpha. Du kannst aber gerne mittesten und auch neue Features vorschlagen.

**Comment by testit2020** [comment]
Auf dem Microsoft Edge lief es erst nicht. Ich habe dann das Widget in VIS genutzt im Firefox. Damit funktionierte es dann. Auch im Microsoft Edge funktionierte es danach. Weiteres ist dem Thread, wie oben beschreiben. Danke.
