### ISSUE TITLE
HTML View

### ISSUE THREAD

**Issue by duczz** [oweitman/ioBroker.tvprogram#25]
Ein HTML-View Datenpunkt wäre noch cool, dann könnte man es auch in andere Views mit einbinden.
Vllt findest du ja die Zeit dafür

**Comment by oweitman** [comment]
das nennt sich widget und ist bereits vorhanden.
ich erzeuge html nie auf der server seite.
wenn du vis selbst nicht nutzt, dann musst du die vorhandenen widgets über ein iframe einbinden.
also in vis eine view mit dem jeweiligen widget drauf.
die webadresse dieses views dann in ein iframe am anderen ort einbinden.

das machen diverse andere bereits ebenso.

**Comment by duczz** [comment]
Alles klar, via Vis will ichs nicht nutzen da ich die einfach unheimlich langsam finde, dann muss ich mir was anderes überlegen
