### ISSUE TITLE
Favoriten DP mit selben Werten wie Record-DP befüllen

### ISSUE THREAD

**Issue by djmarc75** [oweitman/ioBroker.tvprogram#453]
Tag,
super Adapter und funktioniert wie er soll.
Mir würde es aber gefallen wenn der DP "favorites" mit den selbigen Werten wie der DP "record" befüllt wird.
Warum? Ich mag den gelben Stern wenn man eine Sendung als Favorit markiert aber der DP "favorites" nur sehr eingeschränkt verarbeiten kann - z.B. per Skript. Da ist der DP "record" mit den JSON Infos besser geeignet - aber leider ist "record" nicht in der GUI sichtbar.
Hoffe ich hab mich verständlich gemacht :)

Greets

**Comment by oweitman** [comment]
hm, aber vom sinn sind die ja erst mal schon unterschiedlich,
in favorites stehen ja nur sendungsnamen ohne zeit und kanalbezug drin, so das die sendungen, egal auf welchem kanal die gesendet werden im favorites widget. bspw tatort, dann siehst du wo die wiederholungen kommen oder wo auch alte folgen ausgestrahlt werden.

der datenpunkt record enthält ja genau eine sendung zu einem bestimmten Zeitpunkt.
der datenpunkt ist dazu gedacht, das jemand dann die sendung automatisiert auf dem videorecorder programmiert werden kann. gleich im anschluss sollte der eigentlich wieder geleert werden. vgl auch das beispielskript in der hilfe zu "recordlist"

wenn du alle sendungen die aufgezeichnet werden sollen zu den favoriten hinzufügen willst,
dann kannst du einfach einen trigger auf den record-datenpunk (siehe auch hier das script recordlist) setzen und dann das array im datenpunkt favorites ergänzen.
