### ISSUE TITLE
Please remove vis from io-package dependancies

### ISSUE THREAD

**Issue by ldittmar81** [oweitman/ioBroker.tvprogram#671]
This adapter doesn't require VIS to function; it can be used independently without VIS.

**Comment by oweitman** [comment]
but it contains widgets

**Comment by ldittmar81** [comment]
Das mag ja sein, aber ich zum Beispiel nutze diesen und auch den RSS Feed ohne Vis. Die Daten werden dann bei mir im iQontrol angezeigt. Nun ist es so, dass Vis durch Vis-2 ersetzt wird. Meine Vis Instanz würde ich gerne löschen, aber dazu müsste ich deine Adapter auch löschen, was total doof ist, denn die werden ja gebraucht. Beim restartAdapters gebe ich dir Recht. Da muss vis und ggf vis-2 rein, aber nicht bei dependencies... Die Problematik wurde auch beim letzten November Meeting diskutiert (der 7. Punkt):

https://forum.iobroker.net/topic/69715/meeting-f%C3%BCr-iobroker-core-dev-admin-29-11-23-20-30

**Comment by oweitman** [comment]
hm,
hm da steht jetzt nix zur adapterstrategie drin:
also logik, vis1,vis2 jeweils ein separater adapter,
oder alles zusammen mit entsprechenden dependency regeln?
https://github.com/oweitman/ioBroker.mytime/issues/706#issuecomment-1819602674
der beschriebene fall gilt glaube ich für eigentlich alle adapter. keiner brauch vis wirklich, da adapter ja meist nur datenpunkte beschreiben.
also das würde ja eher zum szenario führen, jeweils separate adapter. der reine logik adapter hat nur die abhängigkeit zu iobroker
der jeweilige widget adapter sorgt dafür, das vis1/2 neu gestartet wird und hat dann auch die abhängigkeit zu dem jeweiligen vis. dann auch separate adapter für vis1/vis2 widgets, da ansonsten ja dann jeweilig das andere vis mitinstalliert wird.
dann wären auch weitere adapter für andere visualisierungen (falls sinnig) möglich
wäre das dann deine offizielle aussage? oder müsst ihr das nochmal besprechen

**Comment by Apollon77** [comment]
@oweitman Das Thema kam letztens auf und wir haben folgendes als "Best practice" im Dev-meeting besprochen:
Adapter die NUR Widgets enthalten (und sonst nichts anbieten) - was deiner nicht ist - sollten die entsprechende Vis version als Dev haben ... Wenn Sie in beiden gehen dann aber nicht weil wir das aktuell nicht abbilden können.

Adapter die als Hauptfunktion Daten liefern und _zusätzlich_ Widgets haben (die aber optional für die User sind!) - was bei dem hier wohl eher zutrifft, sollten keine vis abhängigkeit haben weil man Sie ja auch vollständig ohne vis nutzen kann.

**Comment by oweitman** [comment]
Ok

**Comment by oweitman** [comment]
stable fixed ab 2.1.0
