### ISSUE TITLE
getServerBraodcast liefert keine Daten mehr

### ISSUE THREAD

**Issue by mcuiobroker** [oweitman/ioBroker.tvprogram#680]
sendTo("tvprogram.0","getServerBroadcast",{viewdate:"2021-02-10",eventid:"10659522"},(data)=>console.log(data));
Funktioniert nicht mehr.
Es wird nur `getServerBraodcast`ausgegeben

**Versions:**  
 - Adapter version: 1.1.2
 - JS-Controller version: 4.0.24
 - Node version: v18.18.2
 - Operating system: debian

**Additional context**

**Comment by oweitman** [comment]
Dies müsste mit der neuesten Version aus dem beta repo behoben worden sein.
