### ISSUE TITLE
tvprogram seems not to work with VIS-2 (VIS NG)

### ISSUE THREAD

**Issue by Cisalpinos** [oweitman/ioBroker.tvprogram#726]
The Adapter seems not to work with VIS-2. With VIS (means VIS-1) its still working fine.
tvprogram widgets have issues with the new VIS version. 
Reinstall of the adapter and instance didn't help.

Version tvprogram: 1.1.2
Vis-2: 2.9.42 (but also all older versions didn't work)
Vis-1: 1.5.4
Both Vis versions are installed in parallel 

Will the tvprogram adapter get an update to work also VIS-2? 

Errormessage in the log file when using VIS-2 and tvprogram: 

![grafik](https://github.com/oweitman/ioBroker.tvprogram/assets/82289781/d724df04-cde8-4d2f-af72-42374364e03a)

**Comment by oweitman** [comment]
yes this is correct.
in vis-2 some functions missed.
if these are implemented, the i can go ahead to publish my updates.
https://github.com/ioBroker/ioBroker.vis-2/pull/444
if you want you can make a thumb up in the pull request

**Comment by oweitman** [comment]
the PR is merged, but vis-2 with this changes is actualy not released. we have to wait

**Comment by oweitman** [comment]
vgl bitte diese Meldung
https://forum.iobroker.net/topic/40168/test-adapter-tvprogram/844?_=1731810240299
Es ist nun möglich die widgets auch unter vis2>v2.10.7 einzusetzen.
Diese Version kann per Expertenmodus über den Knopf + andere Version installieren geladen werden.
