### ISSUE TITLE
iob 3.3 warnings

### ISSUE THREAD

**Issue by oweitman** [oweitman/ioBroker.tvprogram#74]
<html>
<body>

tvprogram.0 | 2021-05-10 20:29:00.348 | warn | (1402) Read-only state "tvprogram.0.tv1.cmd" has been written without ack-flag with value "new\|program\|2021-05-13"
-- | -- | -- | --
tvprogram.0 | 2021-05-10 20:29:00.342 | warn | (1402) Read-only state "tvprogram.0.tv1.cmd" has been written without ack-flag with value "new\|program\|2021-05-11"
tvprogram.0 | 2021-05-10 20:29:00.327 | warn | (1402) Read-only state "tvprogram.0.tv1.cmd" has been written without ack-flag with value "new\|program\|2021-05-14"
tvprogram.0 | 2021-05-10 20:29:00.326 | warn | (1402) Read-only state "tvprogram.0.tv1.cmd" has been written without ack-flag with value "new\|program\|2021-05-12"
tvprogram.0 | 2021-05-10 20:28:59.967 | warn | (1402) Read-only state "tvprogram.0.tv1.cmd" has been written without ack-flag with value "new\|program\|2021-05-15"
tvprogram.0 | 2021-05-10 20:28:59.865 | warn | (1402) Read-only state "tvprogram.0.tv1.cmd" has been written without ack-flag with value "new\|program\|2021-05-10"
tvprogram.0 | 2021-05-10 20:28:58.032 | warn | (1402) Read-only state "tvprogram.0.tv1.cmd" has been written without ack-flag with value "new\|channels"
tvprogram.0 | 2021-05-10 20:28:57.983 | warn | (1402) Read-only state "tvprogram.0.tv1.cmd" has been written without ack-flag with value "new\|genres"
tvprogram.0 | 2021-05-10 20:28:57.891 | warn | (1402) Read-only state "tvprogram.0.tv1.cmd" has been written without ack-flag with value "new\|categories"

tvprogram.0 | 2021-05-10 20:33:10.876 | warn | (1783) Read-only state "tvprogram.0.tv1.cmd" has been written without ack-flag with value "new\|categories"
-- | -- | -- | --
tvprogram.0 | 2021-05-10 20:33:10.856 | warn | (1783) Read-only state "tvprogram.0.tv1.cmd" has been written without ack-flag with value "new\|channels"
tvprogram.0 | 2021-05-10 20:33:10.834 | warn | (1783) Read-only state "tvprogram.0.tv1.cmd" has been written without ack-flag with value "new\|genres"

</body>
</html>

**Comment by BassT23** [comment]
+1

**Comment by oweitman** [comment]
fixed
